trigger: none

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Test
  jobs: 
  - job: mytest
    steps:
    - task: GoTool@0
      inputs:
        version: '1.14'
    - task: Go@0
      inputs:
        command: 'get'
        arguments: 'github.com/google/go-github/github'